apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: lenka
  labels:
    env: prod
spec:
  nodeName: wn1  # Ensure wn1 has the correct label applied.
  nodeSelector:
    node: wn1  # Matches the nodeName.
  volumes:
    - name: myvol1
      hostPath:
        path: /home/ec2-user/website1  # Ensure this path exists as a directory.
        type: Directory
  containers:
    - name: mycontainer
      image: thala12345/dockertask:lenka  # Ensure this image exists in your Docker Hub.
      volumeMounts:
        - name: myvol1
          mountPath: /var/www/html
          readOnly: true  # Keep it false if the container needs to write to the volume.
      ports:
        - containerPort: 80  # Ensure the application inside the container listens on this port.


